name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project in editable mode
        run: pip install -e .

      - name: Install linting tools
        run: pip install ruff structlog

      - name: Lint with Ruff
        run: ruff check .

  build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.12"]

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Upgrade pip
          run: python -m pip install --upgrade pip

        - name: Install project in editable mode
          run: pip install -e .

        - name: Run tests
          run: pytest
